ReactiveX/RxGo

.travis.yml
README.md
connectable/connectable.go
connectable/connectable_test.go
examples/reactive_sum/sum.go
examples/scroll/server.go
handlers/handlers_test.go
iterable/iterable.go
iterable/iterable_test.go
observable/observable.go
observable/observable_test.go
observer/observer.go
observer/observer_test.go

as in discussion this fix the build and the tests.
https://github.com/ReactiveX/RxGo/issues/19

fix import github.com/jochasinga/rxgo - > github.com/reactivex/rxgo

---

observable/observable.go
observable/observable_test.go

Add Skip & SkipLast

---

observable/observable.go
observable/observable_test.go

#19 first proposal of RX "repeat create operation", we should go in discussion.

Add Repeat operator

---

observable/observable.go
observable/observable_test.go

https://github.com/ReactiveX/RxGo/issues/14

Add Take & TakeLast Filter

---

observable/observable.go
observable/observable_test.go

@pocket7878 add `Take` and `TakeLast` to `Observable`.

Add Take & TakeLast filters (#23)

---

.gitignore
connectable/connectable.go
connectable/connectable_test.go
eventhandler.go
handlers/handlers.go
handlers/handlers_test.go
observable/observable.go
observable/observable_test.go
observer/observer.go
observer/observer_test.go

Pull request backing issue: #28

Proposal - change Observer to interface

---

observable/observable.go
observable/observable_test.go

Add "Merge" operator for observables.
eg.
`
var s1 observable.Observable
var s2 observable.Observable
var s3 observable.Observable
sub := observable.Merge(s1, s2, s3)
`
Test pass

Add "Merge" operator for Observables.

---

fx/fx.go
observable/observable.go
observable/observable_test.go

add combineLatest operator
solve #26

feat(operator): add combineLatest operator

---

subscription/subscription.go

clear subscription comment source

---

README.md

@teivah thank you very much for the contribution and hours devoted to the RxGo project
refs:
- https://github.com/ReactiveX/RxGo/issues/99#issuecomment-443281707
- https://github.com/ReactiveX/RxGo/pull/95

starting developer RxGo version 2

---

README.md

official channel on gitter.im to ReactiveX/RxGo

---

README.md

official channel on gitter.im to ReactiveX/RxGo v2

---

assert.go
assert_test.go
fx.go
observable.go
observable_test.go
observablecreate.go
observablecreate_test.go
single.go

* `Average` operators: `AverageFloat32`, `AverageFloat64`, `AverageInt`, `AverageInt8`, `AverageInt16`, `AverageInt32`, `AverageInt64`
* `Concat` operator
* `Min` and `Max` operators: value calculated according to a given comparator
* Improvement of the assertion API: management of `Single` and `OptionalSingle` types

Math operators: Average, Concat, Min and Max

---

.travis.yml
duration.go
duration_test.go
observable.go
observable_test.go
observer.go
singleobserver.go

[WIP] add race on go test

---

observable.go
observable_test.go

* `SumFloat32`
* `SumFloat64`
* `SumInt64`
Issue reference: https://github.com/ReactiveX/RxGo/issues/152

Sum operator

---

connectableobservable.go
connectableobservable_test.go

Issue: https://github.com/ReactiveX/RxGo/issues/184

Fixing connectable observable dead loop

---

.travis.yml
flatmap.go
go.mod
iterator.go

Based on @dparrish's PR: https://github.com/ReactiveX/RxGo/pull/168

Use a semaphore instead of WaitGroup for FlatMap parallelism

---

README.md
errors.go
factory.go
factory_test.go
go.mod
go.sum
item.go
item_test.go
iterable.go
iterable_channel.go
iterable_create.go
iterable_defer.go
iterable_eventsource.go
iterable_factory.go
iterable_range.go
iterable_slice.go
observable.go
observable_operator.go
observable_operator_test.go
optionalsingle.go
single.go
types.go

* Defer
* Create
* GroupBy
* DoOnNext, DoOnCompleted, DoOnError

New v2 operators

---

assert.go
duration.go
factory.go
factory_test.go
item.go
item_test.go
observable.go
observable_operator.go
observable_operator_test.go
optionalsingle.go
single.go

* Make sure the observable context is propagated while emitting an item for each operator
* Improve testCausality function (not 100% deterministic before)

Context propagation

---

observable_operator.go
observable_operator_test.go

Replaced Unix with UnixNano in Join function.
Changed condition to remove old items from right stream buffer.
Simplified window check condition.

Join function update

---

observable_operator.go
observable_operator_test.go

Fixing https://github.com/ReactiveX/RxGo/issues/234

Fixing time based observable

---

README.md

Fixing docs for "Hot vs Cold Observables"

---

doc/min.md

Use `Min` method in `min` example.

Update min.md for using wrong method

---

README.md
doc/groupby.md
doc/groupbydynamic.md
go.sum
observable.go
observable_operator.go
observable_operator_bench_test.go
observable_operator_test.go
optionalsingle_test.go

https://github.com/ReactiveX/RxGo/issues/253

GroupByDynamic

---

observable_operator.go

Closes https://github.com/ReactiveX/RxGo/issues/260

Do not increment Count operator in case of error

---

doc/timestamp.md

Closes https://github.com/ReactiveX/RxGo/issues/263

Fixing timestamp documentation

---

README.md

Fixing https://github.com/ReactiveX/RxGo/issues/331

Fixing Yomo link

---

observable_operator_test.go

fixed debounce test
