ReactiveX/RxGo

iterable/iterable.go, iterable/iterable_test.go
Iterable support slice, map, chan.
eg.
```go
//slice        
iterable.New([]int{})
iterable.New([]string{})
iterable.New([]interface{}{})
//...any type
//map
iterable.New(map[string]string{})
iterable.New(map[string][]string{})
iterable.New(map[interface{}]interface{})
//...any type
//chan
iterable.New(chan interface{})
iterable.New(chan string)
//...any type
```
Test pass.
=> Iterable support slice/map/chan any type

.gitignore, README.md, examples/flatmap/flatmap_slice_test.go, observable/create.go, observable/flatmap.go, observable/flatmap_test.go, observable/observable.go, observable/observable_test.go, observer/observer_mock.go
I've prepared flatMap operator, which is consistent with current implementation. Feature request issue: #49 Feature Request: FlatMap
=> 49 feature request flatmap

examples/flatmap/flatmap_slice_test.go, observable/create.go, observable/create_test.go
I created this pull request to improve test coverage of `create` operator, I've added to ease example writing. Besides that I corrected behavior of onerror for create operator (onerror signals the terminal state) and the example.
Thanks @avelino for your help.
=> improve test coverage and fix on error behavior

observable/observable.go, observable/observable_test.go, observable/options.go, observable/options_test.go
Hello,
First of, thanks for this project it's awesome.
**Pull request goal:** I wanted to make configurable the number of goroutines created during the subscription to an observable.
**Changes:**
* New `observable.options.go`: Mechanism to handle configurable options. The logic is similar to what we can find for example in the gRPC library ([example](https://github.com/grpc/grpc-go/blob/04ea82009cdb9ecdefc6289f4c93ec919a10b3b6/dialoptions.go)). For the time being, I've added a single concrete option: `WithParallelism` to configure the number of created goroutines.
* Changes to `observable.observable.go`: I changed the `Subscribe` method to get also a list of `Option`. I like this approach because the method remains backward-compatible. If the number of goroutines has been configured, I …
=> Parallelize an observable subscription

connectable/connectable.go, connectable/connectable_test.go, observable/observable.go
Dear committers
I think the `ScannableFunc` at `Scan` should be expected to be executed only once in one iteration.
BR
0x5010
=> fix scan func repetitive operation

duration.go, duration_test.go, observable.go, observable_test.go, observer.go, singleobserver.go
Buffer operators (using a signature very close to https://github.com/ReactiveX/RxGo/issues/36#issue-251782169):
* BufferWithCount
* BufferWithTime
* BufferWithTimeOrCount
+ Race condition fix
=> Buffer operators

assert.go, assert_test.go, iterable/iterable_test.go, observable.go, observable_test.go
`StartWith` operator implementation:
* `StartWithItems` to start from a list of items
* `StartWithIterable` to start from a given `Iterable`
* `StartWithObservable` to start from a given `Observable`
Reference: http://reactivex.io/documentation/operators/startwith.html
Related issue: https://github.com/ReactiveX/RxGo/issues/135
=> StartWith operator

flatmap.go, go.mod, go.sum
See https://github.com/golang/go/wiki/Modules for information on why
this is a "good idea".
=> Add Go 1.11+ module support for Version 2.

errors/errors.go, fx.go, iterator.go, observablecreate.go, observablecreate_test.go
* New `CombineLatest()` operator
* New `cancel()` method on the `Iterator` interface in order to cancel an on-going pull iteration (while pulling items from a channel, we had to signal to the `Iterator` to stop it using a context)
+ Removing failing back-pressure tests (to be fixed in another PR)
=> CombineLatest operator

.travis.yml, errors.go, go.mod, go.sum, iterator.go, observable.go, observablecreate.go, observablecreate_test.go, optional.go, optional_test.go
* Refactoring of some existing errors
* Use of `pkg/errors`
=> Errors management improvement

observer.go, observer_test.go, singleobserver.go, singleobserver_test.go
https://github.com/ReactiveX/RxGo/pull/167
=> Use a channel instead of a mutex for Observer and SingleObserver

connectableobservable.go, observable.go, observable_mock_test.go, observable_test.go, observablecreate.go, observablecreate_test.go
Implementation of a _causality_ testing API based on a DSL. For example:
```go
observables := mockObservables(t, `
1
2
3
4
x
x
`)
```
Each column represents an observable emitting item. The first observable will produce the items `1`, `3` and will close (`x`) whereas the second observable will produce the items `2`, `4` and will close.
This code will produce observables from which iterating over the internal iterator does guarantee sequentiality. It means `1` will be handled before `2`, `2` before `3` etc. regardless of the execution context.
This allows us to get rid of `time.Sleep` in some tests which leads to deterministic tests.
Last but not least, sending an item `e` in the DSL creates pushes an error item.
=> Causality testing API

observable/flatmap.go
FlatMap() generates a closure/goroutine corresponding to each element, which run concurrently depending on the parallelism parameter. However, each closure shares the `sequence` variable, which causes issues when `sequence` is rewritten before the previous value of `sequence` is subscribed to. This causes weird non-deterministic behavior and 'skipping' Observables before they're done.
The fix is to pass each goroutine its own copy of `sequence` at time of creation.
More info on this kind of bug:
https://blog.cloudflare.com/a-go-gotcha-when-closures-and-goroutines-collide/
=> Fix flatmap race condition using incorrect observable from apply()

factory.go, factory_test.go
run each Observable concurrently
fix #242
=> Fix Merge Operator always emit values sequentially

iterable_eventsource.go, observable_operator.go, observable_operator_test.go
Closes https://github.com/ReactiveX/RxGo/issues/262
=> Stopping the Take Operator Stream When it Receives all the Expected Items

doc/groupbydynamic.md, observable.go, observable_operator.go, observable_operator_test.go
https://github.com/ReactiveX/RxGo/issues/264
=> GroupBy dynamic distribution function type change

README.md, doc/error.md, doc/errors.md
Closes https://github.com/ReactiveX/RxGo/issues/269
=> Error documentation

doc/options.md
Very minor typo fix for now, addresses #274 .
**About me**
Still looking at other bug fixes/documentation that I can start with. I come from an rxjs background, and have recently learned Go; so I'm still learning the peculiarities of Golang the language. I am still looking at how I might be able to use RxGo on my projects.
=> 📝 docs: Fixed typo for func call of WithBufferedChannel.

factory.go, factory_connectable_test.go, factory_test.go, iterable_range.go, observable_operator_test.go
Range should generates a sequence of count integers beginning at start.
This change fixes RxGo to be in line as the other imlementations of
RectiveX.
=> Fix Range factory

item.go, item_test.go
SendContext didn't check if context is done first. Instead, in case ctx is done and channel to send has a free buffer, it chose randomly either to return false or send value to the channel.
Added a test that failed randomly on previous version of SendContext.
Changes to be committed:
modified:   item.go
modified:   item_test.go
=> SendContext fix

go.mod, go.sum, iterable_eventsource.go
This change fixes locked up event source iterable obervers which were
waiting for their channels to be closed.  The event source iterable,
using a blocking strategy, could be notified that its context has been
canceled and exit without closing waiting observers' channels.
A deferred function which closes all observers was added to the event
source iterable's go routine, thus ensuring that all the observers'
channels were closed.
=> Fix event source iterable

doc/options.md
The `WithObservationStrategy` documentation section currently specifies
`WithObservation` in the code samples, so this PR updates to resolve the mismatch.
Signed-off-by: Nick Groszewski <groszewn@gmail.com>
=> fix(docs): Fix incorrect WithObservationStrategy reference in docs
